name: Security Checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * 0'  # Elke zondag om middernacht

permissions:
  contents: read
  security-events: write

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety detect-secrets bandit

    - name: Check for vulnerable dependencies
      run: safety check

    - name: Scan for secrets and fail if secrets are found
      run: |
        detect-secrets scan > .secrets.baseline
        # Check if there are any secrets in the baseline, and if so, fail the workflow
        detect-secrets audit .secrets.baseline || (echo "Secrets found!" && exit 1)

    - name: Perform static application security testing (SAST)
      run: bandit -r .
